# https://docs.docker.com/compose/compose-file/
version: '3'
services:
  service-a:
    image: ${SERVICE_A}
    ports:
      - 8081:8080
    networks:
      - local_zone
      - efk
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAEGER_ENDPOINT: ${JAEGER_ENDPOINT}
      FLUENTD_HOST: ${FLUENTD_HOST}
      FLUENTD_PORT: ${FLUENTD_PORT}
      REGION: ${REGION}
      ZONE: ${ZONE}
      SERVICE_NAME: service-a
      VERSION_TAG: ${SERVICE_A}
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:${FLUENTD_PORT}
#        tag: service-a

  service-b:
    image: ${SERVICE_B}
    ports:
      - 8082:8080
    networks:
      - local_zone
      - efk
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAEGER_ENDPOINT: ${JAEGER_ENDPOINT}
      FLUENTD_HOST: ${FLUENTD_HOST}
      FLUENTD_PORT: ${FLUENTD_PORT}
      REGION: ${REGION}
      ZONE: ${ZONE}
      SERVICE_NAME: service-b
      VERSION_TAG: ${SERVICE_B}
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:${FLUENTD_PORT}
#        tag: service-b

# https://docs.docker.com/compose/networking/
networks:
  local_zone:
    driver: bridge
  # https://docs.docker.com/compose/networking/#use-a-pre-existing-network
  efk:
    external:
      name: frtu_efk