version: '3'
services:
  service-a:
    image: ${SERVICE_A}
    ports:
      - 8081:8080
    networks:
      - frtu_efk
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAEGER_ENDPOINT: ${JAEGER_ENDPOINT}
      FLUENTD_HOST: ${FLUENTD_HOST}
      FLUENTD_PORT: ${FLUENTD_PORT}
      REGION: ${REGION}
      ZONE: ${ZONE}
      SERVICE_NAME: service-a
      VERSION_TAG: ${SERVICE_A}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_HOST}:${FLUENTD_PORT}
        tag: service-a

  service-b:
    image: ${SERVICE_B}
    ports:
      - 8082:8080
    networks:
      - frtu_efk
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAEGER_ENDPOINT: ${JAEGER_ENDPOINT}
      FLUENTD_HOST: ${FLUENTD_HOST}
      FLUENTD_PORT: ${FLUENTD_PORT}
      REGION: ${REGION}
      ZONE: ${ZONE}
      SERVICE_NAME: service-b
      VERSION_TAG: ${SERVICE_B}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_HOST}:${FLUENTD_PORT}
        tag: service-b

networks:
  frtu_efk:
    external: true
