version: '3'
services:
  service-a:
    image: ${SERVICE_A}
    ports:
      - 8081:8080
    environment:
      JAEGER_ENDPOINT: http://localhost:14268/api/traces
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service-a

  service-b:
    image: ${SERVICE_B}
    ports:
      - 8082:8080
    environment:
      JAEGER_ENDPOINT: http://localhost:14268/api/traces
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service-b