version: "3.5"
services:
  otel-collector:
    image: ${OTEL_COLLECTOR_IMAGE}
    command: [ "--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}" ]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4317:4317    # OTLP gRPC receiver
      - 4318:4318    # OTLP HTTP receiver
      - 14250:14250  # Jaeger gRPC (bridge)
      # INTERNAL INFRASTRUCTURE PORT
      - 8888         # Prometheus metrics exposed by the collector
      - 8889         # Prometheus exporter metrics
      - 1888         # pprof extension
      - 13133        # health_check extension
      - 55679        # zpages extension
    depends_on:
      - jaeger
      - prometheus
    networks:
      - bridge

  jaeger:
    image: ${JAEGER_IMAGE}
    # https://www.jaegertracing.io/docs/1.35/deployment/
    # https://www.jaegertracing.io/docs/1.35/monitoring/
    ports:
      - 5775/udp        # Jaeger UDP
      - 14251:14250     # Jaeger gRPC (direct)
      - 14268
      - 16686:16686     # Web UI
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
      ES_TAGS_AS_FIELDS_ALL: "true"
    depends_on:
      - elasticsearch
    networks:
      - bridge

  grafana:
    image: ${GRAFANA_IMAGE}
    #    volumes:
    #      - ./grafana.ini:/etc/grafana/grafana.ini
    #      - ~/data/grafana:/var/lib/grafana
    #    environment:
    #      - GF_SECURITY_ADMIN_PASSWORD=YourPassword
    #      - GF_AUTH_DISABLE_LOGIN_FORM=true
    #      - GF_AUTH_ANONYMOUS_ENABLED=true
    #      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    hostname: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - bridge

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus:/etc/prometheus
    #      - ~/data/prometheus:/prometheus
    ports:
      - 9091:9090
    networks:
      - bridge

  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    restart: always
    volumes:
      - ~/data/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - 9200
    environment:
      - node.name=LOGGING
      - discovery.type=single-node
    #      - bootstrap.memory_lock=true
    #      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    healthcheck:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html
      test: [ "CMD", "curl", "--fail", "http://elasticsearch:9200/_cluster/health" ]
      interval: 30s
      timeout: 40s
      retries: 5
      start_period: 40s
    networks:
      - bridge

  kibana:
    image: ${KIBANA_IMAGE}
    restart: always
    ports:
      - 5601
    environment:
      # https://www.elastic.co/guide/en/kibana/current/docker.html
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - bridge

### REPLACED BY OTEL - Metrics ###
# https://blog.pvincent.io/2017/12/prometheus-blog-series-part-3-exposing-and-collecting-metrics/
#  node-exporter:
#    image: ${NODE_EXPORTER_IMAGE}
#    ports:
#      - 9100:9100
#    networks:
#      - bridge
#  alertmanager:
#    image: ${ALERTMANAGER_IMAGE}
#    restart: unless-stopped
#    volumes:
#      - ./alertmanager:/etc/alertmanager
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/alertmanager'
#    expose:
#      - 9093
#    networks:
#      - bridge

### REPLACED BY OTEL - Logs ###
#  fluentbit:
#    image: ${FLUENT_BIT_IMAGE}
#    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
#    volumes:
#      - ./fluent-bit:/fluent-bit/etc/
#    expose:
#      - 24224
#    ports:
#      - 24224
#      - 24224/udp
#    #   UNCOMMENT FOR PULLING ./log folder
#    #    volumes:
#    #      - ./log:/var/log
#    #    command: |
#    #      /fluent-bit/bin/fluent-bit
#    #        -i tail
#    #        -p Refresh_Interval=10
#    #        -p path=/var/log/*.log
#    #        -o es
#    #        -p Host=elasticsearch
#    #        -p Port=9200
#    #        -p Index=fluent_bit
#    #        -p Type=logs
#    networks:
#      - bridge
#  fluentd:
#    image: ${FLUENTD_IMAGE}
#    volumes:
#      - ./fluentd/conf:/etc/fluent
#    #    build: ./fluentd
#    #    volumes:
#    #      - ./fluentd/conf:/fluentd/etc
#    links:
#      - elasticsearch
#    ports:
#      - 24220:24220
#      - 24224:24224
#      - 24224:24224/udp
#      - 9880:9880
#    networks:
#      - bridge
#    environment:
#      ES_PORT_9200_TCP_ADDR: elasticsearch
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1G"
#        max-file: "2"

# https://docs.docker.com/compose/networking/
networks:
  bridge:
    driver: bridge
    # To enable IPv6 uncomment below lines
#    driver_opts:
#        com.docker.network.enable_ipv6: "true"
