# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  # scrape_timeout is set to the global default (10s).
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'my-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
#   - "first_rules.yml"

# A scrape configuration containing exactly endpoints to scrape
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # the address of an application that exposes metrics for prometheus
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

#  - job_name: 'spring-actuator'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#    - targets: ['HOST_IP:8080']

#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - 'alertmanager:9093'
